export const sampleDate = [
  {
    shareImage: "fertilizer",
    title: "UYJ Fertilizer",
    amount: 15000,
    dailyEarnings: 1000,
    totalMonthlyEarnings: 30000,
    duration: 30,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "bottling",
    title: "UYJ Bottling",
    amount: 45000,
    dailyEarnings: 2764,
    totalMonthlyEarnings: 96750,
    duration: 30,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "rice",
    title: "UYJ Rice",
    amount: 248000,
    dailyEarnings: 6377,
    totalMonthlyEarnings: 446400,
    duration: 70,
    maximumShares: 3,
    quantity_sold: 0,
  },
  {
    shareImage: "transport",
    title: "UYJ Transport",
    amount: 30000,
    dailyEarnings: 2100,
    totalMonthlyEarnings: 63000,
    duration: 30,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "semo",
    title: "UYJ Semo",
    amount: 7500,
    dailyEarnings: 475,
    totalMonthlyEarnings: 14250,
    duration: 30,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "flour",
    title: "UYJ Flour",
    amount: 3000,
    dailyEarnings: 190,
    totalMonthlyEarnings: 5700,
    duration: 30,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "construction",
    title: "UYJ Construction",
    amount: 60000,
    dailyEarnings: 3300,
    totalMonthlyEarnings: 132000,
    duration: 40,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "petroleum",
    title: "UYJ Petroleum",
    amount: 75000,
    dailyEarnings: 4312,
    totalMonthlyEarnings: 172500,
    duration: 40,
    maximumShares: 5,
    quantity_sold: 0,
  },
  {
    shareImage: "shipping",
    title: "UYJ Shipping",
    amount: 108000,
    dailyEarnings: 5805,
    totalMonthlyEarnings: 232000,
    duration: 40,
    maximumShares: 1,
    quantity_sold: 0,
  },
  {
    shareImage: "university",
    title: "UYJ University",
    amount: 164000,
    dailyEarnings: 8200,
    totalMonthlyEarnings: 352600,
    duration: 43,
    maximumShares: 5,
    quantity_sold: 0,
  },
];

export const statSampleDate = {
  total_shares_sold: 0,
  total_users: 0,
  total_amount_invested_in_shares: 0,
  total_earning_on_shares: 0,
  total_shares: 0,
  total_deposits: 0,
  total_withdrawals: 0,
  total_amount_deposited: 0,
  total_amount_earned: 0,
  total_amount_withdrawn: 0,
  total_orders: 0,
};
